services:
  mongo:
    image: mongo:7
    container_name: snapurl-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: snapurl-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/snapurl
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 7d
      NODE_ENV: production
      ORIGIN: http://localhost
      RESEND_API_KEY: ${RESEND_API_KEY}
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: snapurl-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo_data:
